import assert from "node:assert/strict";
import { test } from "node:test";
import {
	assignOrderKeys,
	orderKeyBetween,
	sparseOrderKey,
} from "../lib/board/core/order-key.ts";

/**
 * The contract these tests defend: a node's order key sorts *lexicographically*
 * into its document position, and an edit re-keys only what it must.
 *
 * The second half matters as much as the first. Keys used to be the node's padded
 * array index, so deleting one node rewrote every key after it — thousands of node
 * patches for a one-node edit, past the server's per-transaction cap.
 */

/** Assign keys for `ids`, tracking state the way a real caller does. */
function assign(ids: string[], keys: Map<string, string>) {
	const changed = assignOrderKeys(
		ids.length,
		(index) => ids[index] as string,
		(index) => keys.get(ids[index] as string) ?? null,
	);
	for (const [id, key] of changed) keys.set(id, key);
	for (const id of [...keys.keys()]) if (!ids.includes(id)) keys.delete(id);
	return changed;
}

/** Order the ids by their key, as the server's `ORDER BY order_key` would. */
function sortedByKey(ids: string[], keys: Map<string, string>) {
	return [...ids].sort((a, b) => {
		const ka = keys.get(a) ?? "";
		const kb = keys.get(b) ?? "";
		return ka < kb ? -1 : ka > kb ? 1 : 0;
	});
}

test("a midpoint sorts strictly between its neighbours", () => {
	const cases: Array<[string | null, string | null]> = [
		["00004096", "00008192"],
		["00004096", "00004097"],
		["00000001", "00000002"],
		["0", "1"],
		[null, "00004096"],
		["00004096", null],
		[null, null],
		["99999999", null],
		["00004096", "000040965"],
	];
	for (const [before, after] of cases) {
		const key = orderKeyBetween(before, after);
		assert.ok(key !== null, `expected a key between ${before} and ${after}`);
		if (before !== null) {
			assert.ok(key > before, `${key} must sort after ${before}`);
		}
		if (after !== null) {
			assert.ok(key < after, `${key} must sort before ${after}`);
		}
	}
});

test("no key exists below zero, and callers are told so", () => {
	// Nothing sorts between "" and "0"; the caller renumbers instead of guessing.
	assert.equal(orderKeyBetween(null, "0"), null);
	// Inverted or equal bounds are rejected rather than producing a bogus key.
	assert.equal(orderKeyBetween("00008192", "00004096"), null);
	assert.equal(orderKeyBetween("00004096", "00004096"), null);
});

test("numeric stepping never inverts lexicographic order", () => {
	// The trap: "4101" is numerically larger than "5" but sorts before it. A key
	// generated by arithmetic must keep its width, or ordering silently breaks.
	let previous = orderKeyBetween(null, null) as string;
	for (let i = 0; i < 500; i += 1) {
		const next = orderKeyBetween(previous, null) as string;
		assert.ok(next !== null);
		assert.ok(
			next > previous,
			`step ${i}: ${next} must sort after ${previous}`,
		);
		previous = next;
	}
});

test("a fresh numbering is uniform width and correctly ordered", () => {
	// Width has to be chosen for the whole run: a run that outgrows its width would
	// wrap into a shorter-but-larger string and invert.
	for (const count of [1, 10, 10_000, 50_000]) {
		const keys = Array.from({ length: count }, (_, index) =>
			sparseOrderKey(index, count),
		);
		const widths = new Set(keys.map((key) => key.length));
		assert.equal(
			widths.size,
			1,
			`count ${count} produced widths ${[...widths]}`,
		);
		for (let i = 1; i < keys.length; i += 1) {
			assert.ok(
				(keys[i] as string) > (keys[i - 1] as string),
				`count ${count}: key ${i} out of order`,
			);
		}
	}
});

test("an edit that does not reorder re-keys nothing", () => {
	const ids = ["a", "b", "c", "d"];
	const keys = new Map<string, string>();
	assign(ids, keys);
	// Same order again: no work, so no node patches.
	assert.equal(assign(ids, keys).size, 0);
});

test("deleting a node leaves every other key untouched", () => {
	const ids = Array.from({ length: 200 }, (_, index) => `n${index}`);
	const keys = new Map<string, string>();
	assign(ids, keys);
	const before = new Map(keys);

	// Delete the *first* node: the worst case for index-derived keys, which would
	// have rewritten all 199 remaining ones.
	const remaining = ids.slice(1);
	const changed = assign(remaining, keys);
	assert.equal(changed.size, 0);
	for (const id of remaining) assert.equal(keys.get(id), before.get(id));
	assert.deepEqual(sortedByKey(remaining, keys), remaining);
});

test("appending and inserting each re-key at most the new node", () => {
	const ids = Array.from({ length: 100 }, (_, index) => `n${index}`);
	const keys = new Map<string, string>();
	assign(ids, keys);

	for (const at of [ids.length, 50, 0]) {
		const working = [...ids];
		const workingKeys = new Map(keys);
		const id = `new-${at}`;
		working.splice(at, 0, id);
		const changed = assign(working, workingKeys);
		// Only the inserted node needs a key.
		assert.deepEqual([...changed.keys()], [id], `insert at ${at}`);
		assert.deepEqual(sortedByKey(working, workingKeys), working);
	}
});

test("moving one node re-keys only that node", () => {
	const ids = Array.from({ length: 100 }, (_, index) => `n${index}`);
	const keys = new Map<string, string>();
	assign(ids, keys);

	// Send the last node to the front (z-order "send to back"). Keeping keys
	// greedily from the left would rewrite ~everything here; the longest increasing
	// run is what keeps it to one.
	const moved = [ids[99] as string, ...ids.slice(0, 99)];
	const changed = assign(moved, new Map(keys));
	assert.equal(changed.size, 1);

	// And the other direction.
	const toBack = [...ids.slice(1), ids[0] as string];
	assert.equal(assign(toBack, new Map(keys)).size, 1);
});

test("keys written by earlier versions keep working without a migration", () => {
	// Legacy keys were the padded array index, so gaps are 1 — the tightest case.
	const ids = Array.from({ length: 50 }, (_, index) => `n${index}`);
	const keys = new Map(
		ids.map((id, index) => [id, String(index).padStart(8, "0")]),
	);

	// A delete must not need to renumber anything.
	const afterDelete = ids.slice(1);
	assert.equal(assign(afterDelete, new Map(keys)).size, 0);

	// An insert between two adjacent legacy keys must still find room.
	const working = [...ids];
	const workingKeys = new Map(keys);
	working.splice(25, 0, "inserted");
	const changed = assign(working, workingKeys);
	assert.deepEqual([...changed.keys()], ["inserted"]);
	assert.deepEqual(sortedByKey(working, workingKeys), working);
});

test("order survives thousands of random edits", () => {
	// The scenario tests above each check one shape of edit. This checks the thing
	// that actually matters — that no sequence of edits can desynchronise the keys
	// from the document order — and is what caught the width-inversion bug.
	let seed = 20240611;
	const random = (n: number) => {
		seed = (seed * 1103515245 + 12345) & 0x7fffffff;
		return seed % n;
	};

	let ids = Array.from({ length: 12 }, (_, index) => `n${index}`);
	const keys = new Map<string, string>();
	assign(ids, keys);
	let counter = 0;
	let longestKey = 0;

	for (let step = 0; step < 4000; step += 1) {
		const kind = random(3);
		if (kind === 0 && ids.length > 1) {
			ids.splice(random(ids.length), 1);
		} else if (kind === 1) {
			ids.splice(random(ids.length + 1), 0, `x${counter++}`);
		} else if (ids.length > 1) {
			const [moved] = ids.splice(random(ids.length), 1);
			ids.splice(random(ids.length + 1), 0, moved as string);
		}

		assign(ids, keys);
		assert.deepEqual(
			sortedByKey(ids, keys),
			ids,
			`document order lost at step ${step}`,
		);
		// Duplicates would make the server's ordering non-deterministic.
		assert.equal(new Set(ids.map((id) => keys.get(id))).size, ids.length);
		for (const key of keys.values())
			longestKey = Math.max(longestKey, key.length);
	}
	// Keys must not creep upward without bound.
	assert.ok(longestKey < 32, `keys grew to ${longestKey} characters`);
});
